# Generated by Django 6.0 on 2026-02-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jesters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jester',
            name='discord_avatar_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
