# Generated by Django 5.2.8 on 2026-02-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jesters', '0002_jester_discord_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jester',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='jester',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
