# Generated by Django 6.0 on 2026-03-03 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jesters', '0003_alter_jester_avatar_alter_jester_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jester',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Autoproxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='Fluxer User ID', max_length=50)),
                ('channel_id', models.CharField(help_text='Fluxer Channel ID', max_length=50)),
                ('jester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jesters.jester')),
            ],
            options={
                'unique_together': {('user_id', 'channel_id')},
            },
        ),
    ]
