# Generated by Django 6.0 on 2026-03-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jesters', '0004_alter_jester_id_autoproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='JesterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='group_images/')),
                ('discord_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(help_text='Fluxer User ID', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='jester',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jester',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jester',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='jesters', to='jesters.jestergroup'),
        ),
    ]
