# Generated by Django 6.0 on 2026-03-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jesters', '0006_changelog_report_reportcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jester',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature Request'), ('question', 'Question'), ('other', 'Other')], default='bug', max_length=20),
        ),
    ]
