# Generated by Django 6.0 on 2026-03-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jesters', '0007_jester_message_count_report_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jester',
            name='discord_avatar_url',
        ),
        migrations.RemoveField(
            model_name='jestergroup',
            name='discord_image_url',
        ),
        migrations.AddField(
            model_name='jester',
            name='fluxer_avatar_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jestergroup',
            name='fluxer_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
