# Generated by Django 6.0 on 2026-05-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jesters', '0008_remove_jester_discord_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jester',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jestergroup',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
