# Generated by Django 6.0 on 2026-03-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxeruser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fluxeruser',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
